In [1]:
import pandas as pd

In [44]:
merged_df = pd.read_csv('../raw_data/merged2.csv')

In [45]:
merged_df.head()

,Unnamed: 0,Crime ID,Month,Falls within,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,9064997,NaN,2018-06-01,Avon and Somerset Constabulary,-2.509930,51.410873,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN
1,9065002,NaN,2018-06-01,Avon and Somerset Constabulary,-2.516919,51.423683,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN
2,9065003,d07e88b32ac6b7684c493f1a05a3949ed6859031db0262...,2018-06-01,Avon and Somerset Constabulary,-2.509930,51.410873,E01014399,Bath and North East Somerset 001A,Criminal damage and arson,Unable to prosecute suspect,NaN
3,9065004,a131b2d13dd749055ecd03f54ed7b3d69d3313dca1837e...,2018-06-01,Avon and Somerset Constabulary,-2.510162,51.410998,E01014399,Bath and North East Somerset 001A,Criminal damage and arson,Status update unavailable,NaN
4,9065005,d8287c64a02011675e6113ae0fb159cb45336308994248...,2018-06-01,Avon and Somerset Constabulary,-2.509930,51.410873,E01014399,Bath and North East Somerset 001A,Other theft,Status update unavailable,NaN

In [46]:
#Reduce to only the columns that interest us:
merged_df = merged_df.drop(columns = ['Unnamed: 0','Month','Falls within','LSOA code','LSOA name','Context'])
merged_df.head()

,Crime ID,Longitude,Latitude,Crime type,Last outcome category
0,NaN,-2.509930,51.410873,Anti-social behaviour,NaN
1,NaN,-2.516919,51.423683,Anti-social behaviour,NaN
2,d07e88b32ac6b7684c493f1a05a3949ed6859031db0262...,-2.509930,51.410873,Criminal damage and arson,Unable to prosecute suspect
3,a131b2d13dd749055ecd03f54ed7b3d69d3313dca1837e...,-2.510162,51.410998,Criminal damage and arson,Status update unavailable
4,d8287c64a02011675e6113ae0fb159cb45336308994248...,-2.509930,51.410873,Other theft,Status update unavailable

In [47]:
merged_df['Last outcome category'].fillna('no outcome', inplace = True)
merged_df['Crime ID'].fillna('no id', inplace = True)
merged_df.head()

,Crime ID,Longitude,Latitude,Crime type,Last outcome category
0,no id,-2.509930,51.410873,Anti-social behaviour,no outcome
1,no id,-2.516919,51.423683,Anti-social behaviour,no outcome
2,d07e88b32ac6b7684c493f1a05a3949ed6859031db0262...,-2.509930,51.410873,Criminal damage and arson,Unable to prosecute suspect
3,a131b2d13dd749055ecd03f54ed7b3d69d3313dca1837e...,-2.510162,51.410998,Criminal damage and arson,Status update unavailable
4,d8287c64a02011675e6113ae0fb159cb45336308994248...,-2.509930,51.410873,Other theft,Status update unavailable

In [48]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17526680 entries, 0 to 17526679
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Longitude              float64
 2   Latitude               float64
 3   Crime type             object
 4   Last outcome category  object
dtypes: float64(2), object(3)
memory usage: 668.6+ MB

In [51]:
dtype_change = {'Crime ID':'string','Longitude':'float32','Latitude':'float32','Crime type':'category','Last outcome category':'category'}
dtype_change

{'Crime ID': 'string',
 'Longitude': 'float32',
 'Latitude': 'float32',
 'Crime type': 'category',
 'Last outcome category': 'category'}

In [52]:
merged_df.astype(dtype_change).dtypes

Crime ID                   string
Longitude                 float32
Latitude                  float32
Crime type               category
Last outcome category    category
dtype: object

In [53]:
merged_df = merged_df.astype(dtype_change)

In [54]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17526680 entries, 0 to 17526679
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               string
 1   Longitude              float32
 2   Latitude               float32
 3   Crime type             category
 4   Last outcome category  category
dtypes: category(2), float32(2), string(1)
memory usage: 300.9 MB

In [56]:
merged_df.columns = ['id','lon','lat','crime','outcome']

In [57]:
merged_df.head()

,id,lon,lat,crime,outcome
0,no id,-2.509930,51.410873,Anti-social behaviour,no outcome
1,no id,-2.516919,51.423683,Anti-social behaviour,no outcome
2,d07e88b32ac6b7684c493f1a05a3949ed6859031db0262...,-2.509930,51.410873,Criminal damage and arson,Unable to prosecute suspect
3,a131b2d13dd749055ecd03f54ed7b3d69d3313dca1837e...,-2.510162,51.410999,Criminal damage and arson,Status update unavailable
4,d8287c64a02011675e6113ae0fb159cb45336308994248...,-2.509930,51.410873,Other theft,Status update unavailable

In [58]:
merged_df.to_pickle('../raw_data/prediction_unclean_data.csv')

In [63]:
merged_df['crime'].value_counts()

Violence and sexual offences    5569303
Anti-social behaviour           2955766
Criminal damage and arson       1553163
Other theft                     1336553
Public order                    1315264
Vehicle crime                   1190756
Burglary                        1009112
Shoplifting                      911428
Drugs                            537921
Other crime                      311400
Bicycle theft                    247424
Theft from the person            241054
Robbery                          216116
Possession of weapons            131420
Name: crime, dtype: int64

In [64]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17526680 entries, 0 to 17526679
Data columns (total 5 columns):
 #   Column   Dtype
---  ------   -----
 0   id       string
 1   lon      float32
 2   lat      float32
 3   crime    category
 4   outcome  category
dtypes: category(2), float32(2), string(1)
memory usage: 300.9 MB

In [62]:
total_rows = merged_df.shape[0]
total_rows

17526680

In [65]:
outcomes_df = pd.DataFrame(merged_df['outcome'].value_counts())
outcomes_df

                                                    outcome
Investigation complete; no suspect identified       5408119
Unable to prosecute suspect                         4275123
no outcome                                          3325400
Status update unavailable                           1964309
Court result unavailable                             696305
Under investigation                                  534382
Local resolution                                     320437
Awaiting court outcome                               181913
Offender given a caution                             165296
Further investigation is not in the public inte...   151122
Action to be taken by another organisation           138641
Formal action is not in the public interest           99018
Offender given a drugs possession warning             46928
Offender sent to prison                               36506
Offender given penalty notice                         33380
Offender given community sentence                     33315
Further action is not in the public interest          23768
Offender fined                                        18714
Defendant found not guilty                            16788
Offender given suspended prison sentence              12554
Court case unable to proceed                          11722
Offender given conditional discharge                  11620
Suspect charged as part of another case               10700
Offender otherwise dealt with                          3989
Offender ordered to pay compensation                   3463
Defendant sent to Crown Court                          1492
Offender deprived of property                          1386
Offender given absolute discharge                       290

In [66]:
type(outcomes_df)

pandas.core.frame.DataFrame

In [67]:
outcomes_df['percent'] = outcomes_df['outcome'].apply(lambda x: round(int(x)*100/total_rows,2))
outcomes_df

                                                    outcome  percent
Investigation complete; no suspect identified       5408119    30.86
Unable to prosecute suspect                         4275123    24.39
no outcome                                          3325400    18.97
Status update unavailable                           1964309    11.21
Court result unavailable                             696305     3.97
Under investigation                                  534382     3.05
Local resolution                                     320437     1.83
Awaiting court outcome                               181913     1.04
Offender given a caution                             165296     0.94
Further investigation is not in the public inte...   151122     0.86
Action to be taken by another organisation           138641     0.79
Formal action is not in the public interest           99018     0.56
Offender given a drugs possession warning             46928     0.27
Offender sent to prison                               36506     0.21
Offender given penalty notice                         33380     0.19
Offender given community sentence                     33315     0.19
Further action is not in the public interest          23768     0.14
Offender fined                                        18714     0.11
Defendant found not guilty                            16788     0.10
Offender given suspended prison sentence              12554     0.07
Court case unable to proceed                          11722     0.07
Offender given conditional discharge                  11620     0.07
Suspect charged as part of another case               10700     0.06
Offender otherwise dealt with                          3989     0.02
Offender ordered to pay compensation                   3463     0.02
Defendant sent to Crown Court                          1492     0.01
Offender deprived of property                          1386     0.01
Offender given absolute discharge                       290     0.00

In [68]:
outcomes_df['percent'].sum()

100.01

In [69]:
outcomes_df.shape

(28, 2)